"""empty message

Revision ID: e3d7221e01ab
Revises: 
Create Date: 2020-05-20 14:13:25.558796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3d7221e01ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_index('admin_roles_name_unique', table_name='admin_roles')
    op.drop_index('admin_roles_slug_unique', table_name='admin_roles')
    op.drop_table('admin_roles')
    op.drop_index('auth_group_permissions_group_id_permission_id_0cd325b0_uniq', table_name='auth_group_permissions')
    op.drop_table('auth_group_permissions')
    op.drop_index('detail_id_idx', table_name='role_has_detail')
    op.drop_index('role_id_idx', table_name='role_has_detail')
    op.drop_table('role_has_detail')
    op.drop_index('django_content_type_app_label_model_76bd3d3b_uniq', table_name='django_content_type')
    op.drop_table('django_content_type')
    op.drop_index('category_id_idx', table_name='category_has_product')
    op.drop_index('product_id_idx', table_name='category_has_product')
    op.drop_table('category_has_product')
    op.drop_index('auth_user_user_permissions_user_id_permission_id_14a6b632_uniq', table_name='auth_user_user_permissions')
    op.drop_table('auth_user_user_permissions')
    op.drop_table('failed_jobs')
    op.drop_index('auth_user_groups_user_id_group_id_94350c0c_uniq', table_name='auth_user_groups')
    op.drop_table('auth_user_groups')
    op.drop_index('ask_id', table_name='match')
    op.drop_index('offer_id', table_name='match')
    op.drop_table('match')
    op.drop_index('admin_operation_log_user_id_index', table_name='admin_operation_log')
    op.drop_table('admin_operation_log')
    op.drop_table('deparment')
    op.drop_table('help_desk')
    op.drop_table('notification')
    op.drop_index('ratings_rateable_id_index', table_name='ratings')
    op.drop_index('ratings_rateable_type_index', table_name='ratings')
    op.drop_index('ratings_rateable_type_rateable_id_index', table_name='ratings')
    op.drop_table('ratings')
    op.drop_index('name', table_name='auth_group')
    op.drop_table('auth_group')
    op.drop_table('posts')
    op.drop_index('auth_permission_content_type_id_codename_01ab375a_uniq', table_name='auth_permission')
    op.drop_table('auth_permission')
    op.drop_index('username', table_name='auth_user')
    op.drop_table('auth_user')
    op.drop_table('admin_products')
    op.drop_index('fk_deal_transaction1_idx', table_name='deal')
    op.drop_table('deal')
    op.drop_index('admin_permissions_name_unique', table_name='admin_permissions')
    op.drop_index('admin_permissions_slug_unique', table_name='admin_permissions')
    op.drop_table('admin_permissions')
    op.drop_index('admin_role_users_role_id_user_id_index', table_name='admin_role_users')
    op.drop_table('admin_role_users')
    op.drop_table('detail')
    op.drop_table('role')
    op.drop_table('user_notification')
    op.drop_index('admin_role_menu_role_id_menu_id_index', table_name='admin_role_menu')
    op.drop_table('admin_role_menu')
    op.drop_index('category_help_id_idx', table_name='question_answer')
    op.drop_table('question_answer')
    op.drop_index('slug', table_name='category')
    op.drop_table('category')
    op.drop_index('email_address', table_name='users')
    op.drop_table('users')
    op.drop_table('verification')
    op.drop_table('migrations')
    op.drop_table('django_migrations')
    op.drop_table('admin_menu')
    op.drop_index('category_help_id_idx', table_name='category_help')
    op.drop_index('category_help_sluggable_idx', table_name='category_help')
    op.drop_table('category_help')
    op.drop_table('django_admin_log')
    op.drop_index('password_resets_email_index', table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_index('admin_role_permissions_role_id_permission_id_index', table_name='admin_role_permissions')
    op.drop_table('admin_role_permissions')
    op.drop_table('myapi_product')
    op.drop_index('admin_user_permissions_user_id_permission_id_index', table_name='admin_user_permissions')
    op.drop_table('admin_user_permissions')
    op.drop_index('django_session_expire_date_a5c62663', table_name='django_session')
    op.drop_table('django_session')
    op.drop_index('email_address', table_name='customer')
    op.drop_index('username', table_name='customer')
    op.drop_table('customer')
    op.drop_table('email')
    op.drop_index('admin_users_username_unique', table_name='admin_users')
    op.drop_table('admin_users')
    op.alter_column('brand', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('brand', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('brand', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('brand', 'users_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.drop_index('slug', table_name='brand')
    op.create_unique_constraint(None, 'brand', ['id'])
    op.drop_constraint('users_id', 'brand', type_='foreignkey')
    op.alter_column('media_storage', 'product_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('media_storage', 'url',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.create_unique_constraint(None, 'media_storage', ['id'])
    op.drop_constraint('transaction_id', 'media_storage', type_='foreignkey')
    op.drop_constraint('fk_media_storage_verification1', 'media_storage', type_='foreignkey')
    op.alter_column('model_cat', 'brand_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('model_cat', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('model_cat', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('model_cat', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('model_cat', 'users_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.drop_index('slug', table_name='model_cat')
    op.create_unique_constraint(None, 'model_cat', ['id'])
    op.drop_constraint('model_cat_model_cat_id_model_cat_id', 'model_cat', type_='foreignkey')
    op.drop_constraint('fk_model_cat_user1', 'model_cat', type_='foreignkey')
    op.alter_column('product', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('product', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('product', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('product', 'users_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('product', 'visit',
               existing_type=mysql.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.drop_index('slug', table_name='product')
    op.create_unique_constraint(None, 'product', ['id'])
    op.drop_constraint('fk_product_user1', 'product', type_='foreignkey')
    op.alter_column('product_detail', 'product_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.create_unique_constraint(None, 'product_detail', ['id'])
    op.drop_constraint('product_detail_product_id_product_id', 'product_detail', type_='foreignkey')
    op.drop_constraint('product_detail_sizes_shoes_id_sizes_shoes_id', 'product_detail', type_='foreignkey')
    op.create_foreign_key(None, 'product_detail', 'product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'product_detail', 'sizes_shoes', ['sizes_shoes_id'], ['id'])
    op.alter_column('sizes_shoes', 'brand_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('sizes_shoes', 'cm',
               existing_type=mysql.FLOAT(precision=5, scale=1),
               nullable=True)
    op.alter_column('sizes_shoes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('sizes_shoes', 'europe',
               existing_type=mysql.FLOAT(precision=5, scale=1),
               nullable=True)
    op.alter_column('sizes_shoes', 'inch',
               existing_type=mysql.FLOAT(precision=5, scale=1),
               nullable=True)
    op.alter_column('sizes_shoes', 'sizes_types_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('sizes_shoes', 'uk',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('sizes_shoes', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('sizes_shoes', 'us',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('sizes_shoes', 'users_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.create_unique_constraint(None, 'sizes_shoes', ['id'])
    op.drop_constraint('sizes_shoes_brand_id_brand_id', 'sizes_shoes', type_='foreignkey')
    op.drop_constraint('fk_sizes_shoes_user1', 'sizes_shoes', type_='foreignkey')
    op.create_foreign_key(None, 'sizes_shoes', 'brand', ['brand_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sizes_shoes', type_='foreignkey')
    op.create_foreign_key('fk_sizes_shoes_user1', 'sizes_shoes', 'users', ['users_id'], ['id'])
    op.create_foreign_key('sizes_shoes_brand_id_brand_id', 'sizes_shoes', 'brand', ['brand_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'sizes_shoes', type_='unique')
    op.alter_column('sizes_shoes', 'users_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('sizes_shoes', 'us',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('sizes_shoes', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('sizes_shoes', 'uk',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('sizes_shoes', 'sizes_types_id',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('sizes_shoes', 'inch',
               existing_type=mysql.FLOAT(precision=5, scale=1),
               nullable=False)
    op.alter_column('sizes_shoes', 'europe',
               existing_type=mysql.FLOAT(precision=5, scale=1),
               nullable=False)
    op.alter_column('sizes_shoes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('sizes_shoes', 'cm',
               existing_type=mysql.FLOAT(precision=5, scale=1),
               nullable=False)
    op.alter_column('sizes_shoes', 'brand_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'product_detail', type_='foreignkey')
    op.drop_constraint(None, 'product_detail', type_='foreignkey')
    op.create_foreign_key('product_detail_sizes_shoes_id_sizes_shoes_id', 'product_detail', 'sizes_shoes', ['sizes_shoes_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('product_detail_product_id_product_id', 'product_detail', 'product', ['product_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'product_detail', type_='unique')
    op.alter_column('product_detail', 'product_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.create_foreign_key('fk_product_user1', 'product', 'users', ['users_id'], ['id'])
    op.drop_constraint(None, 'product', type_='unique')
    op.create_index('slug', 'product', ['slug', 'name'], unique=True)
    op.alter_column('product', 'visit',
               existing_type=mysql.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('product', 'users_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('product', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('product', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('product', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_foreign_key('fk_model_cat_user1', 'model_cat', 'users', ['users_id'], ['id'])
    op.create_foreign_key('model_cat_model_cat_id_model_cat_id', 'model_cat', 'model_cat', ['model_cat_id'], ['id'])
    op.drop_constraint(None, 'model_cat', type_='unique')
    op.create_index('slug', 'model_cat', ['slug', 'name'], unique=True)
    op.alter_column('model_cat', 'users_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('model_cat', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('model_cat', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('model_cat', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('model_cat', 'brand_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.create_foreign_key('fk_media_storage_verification1', 'media_storage', 'verification', ['verification_id'], ['id'])
    op.create_foreign_key('transaction_id', 'media_storage', 'transaction', ['transaction_id'], ['id'])
    op.drop_constraint(None, 'media_storage', type_='unique')
    op.alter_column('media_storage', 'url',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('media_storage', 'product_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.create_foreign_key('users_id', 'brand', 'users', ['users_id'], ['id'])
    op.drop_constraint(None, 'brand', type_='unique')
    op.create_index('slug', 'brand', ['slug', 'name'], unique=True)
    op.alter_column('brand', 'users_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('brand', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('brand', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('brand', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_table('admin_users',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=190), nullable=False),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=60), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('avatar', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('remember_token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('admin_users_username_unique', 'admin_users', ['username'], unique=True)
    op.create_table('email',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('users_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('subject', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('text', mysql.TEXT(), nullable=False),
    sa.Column('copy', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='fk_email_user1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('oauth_provider', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('oauth_uid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('biography', mysql.TEXT(), nullable=True),
    sa.Column('code_phone', mysql.TEXT(), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('code_country', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('email_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('salt', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('formatted_address', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('viewport', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('route', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('street_number', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('postal_code', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('locality', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('country_short', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('administrative_area_level_1', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('is_email', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('is_phone', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('is_google', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('is_facebook', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.Column('instagram', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('twitter', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('facebook', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('youtube', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('username', 'customer', ['username'], unique=True)
    op.create_index('email_address', 'customer', ['email_address'], unique=True)
    op.create_table('django_session',
    sa.Column('session_key', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('session_data', mysql.LONGTEXT(), nullable=False),
    sa.Column('expire_date', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('session_key')
    )
    op.create_index('django_session_expire_date_a5c62663', 'django_session', ['expire_date'], unique=False)
    op.create_table('admin_user_permissions',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True)
    )
    op.create_index('admin_user_permissions_user_id_permission_id_index', 'admin_user_permissions', ['user_id', 'permission_id'], unique=False)
    op.create_table('myapi_product',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name_1', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('brand_id_1', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('brief_description_1', mysql.LONGTEXT(), nullable=False),
    sa.Column('retail_price_1', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('release_date_1', sa.DATE(), nullable=False),
    sa.Column('colorway_1', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('stlye_1', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('weight_1', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('visit_1', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_active_1', mysql.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('seo_title_1', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('seo_keywords_1', mysql.LONGTEXT(), nullable=False),
    sa.Column('lowest_ask_1', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('lowest_ask_date_1', sa.DATE(), nullable=False),
    sa.Column('highest_offer_1', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('recently_viewed_1', sa.DATE(), nullable=False),
    sa.Column('created_at_1', sa.DATE(), nullable=False),
    sa.Column('updated_at_1', sa.DATE(), nullable=False),
    sa.Column('slug_1', mysql.VARCHAR(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_role_permissions',
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True)
    )
    op.create_index('admin_role_permissions_role_id_permission_id_index', 'admin_role_permissions', ['role_id', 'permission_id'], unique=False)
    op.create_table('password_resets',
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True)
    )
    op.create_index('password_resets_email_index', 'password_resets', ['email'], unique=False)
    op.create_table('django_admin_log',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('object_id', mysql.LONGTEXT(), nullable=True),
    sa.Column('object_repr', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('action_flag', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('change_message', mysql.LONGTEXT(), nullable=False),
    sa.Column('content_type_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`action_flag` >= 0)', name='django_admin_log_chk_1'),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='django_admin_log_content_type_id_c4bce8eb_fk_django_co'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='django_admin_log_user_id_c564eba6_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_help',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('category_help_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('seo_title', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('seo_description', mysql.VARCHAR(length=160), nullable=True),
    sa.Column('seo_keywords', mysql.TEXT(), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('favicon', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('posicion_order', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_help_id'], ['category_help.id'], name='category_help_category_help_id_category_help_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('category_help_sluggable_idx', 'category_help', ['slug', 'name'], unique=True)
    op.create_index('category_help_id_idx', 'category_help', ['category_help_id'], unique=False)
    op.create_table('admin_menu',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('parent_id', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('order', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('icon', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('uri', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('permission', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('django_migrations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('app', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('applied', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('migrations',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('migration', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('batch', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=False),
    sa.Column('type', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('observation', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('match_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('users_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], name='fk_verification_match1'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='fk_verification_user1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('role_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email_verified_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('remember_token', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='fk_users_role1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('email_address', 'users', ['email'], unique=True)
    op.create_table('category',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('seo_title', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('seo_description', mysql.VARCHAR(length=160), nullable=True),
    sa.Column('seo_keywords', mysql.TEXT(), nullable=True),
    sa.Column('shortcut', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('favicon', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('posicion_order', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('url', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='category_category_id_category_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('slug', 'category', ['slug', 'name'], unique=True)
    op.create_table('question_answer',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('category_help_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('question', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('answer', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('posicion_order', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['category_help_id'], ['category_help.id'], name='question_answer_category_help_id_category_help_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('category_help_id_idx', 'question_answer', ['category_help_id'], unique=False)
    op.create_table('admin_role_menu',
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('menu_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True)
    )
    op.create_index('admin_role_menu_role_id_menu_id_index', 'admin_role_menu', ['role_id', 'menu_id'], unique=False)
    op.create_table('user_notification',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('customer_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('notification_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('is_active_num', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='customer_id'),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], name='notification_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_role_users',
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True)
    )
    op.create_index('admin_role_users_role_id_user_id_index', 'admin_role_users', ['role_id', 'user_id'], unique=False)
    op.create_table('admin_permissions',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('slug', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('http_method', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('http_path', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('admin_permissions_slug_unique', 'admin_permissions', ['slug'], unique=True)
    op.create_index('admin_permissions_name_unique', 'admin_permissions', ['name'], unique=True)
    op.create_table('deal',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('conditions', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('box', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.FLOAT(precision=18, scale=2), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('product_detail_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('type_transaction', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('images', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('transactioncol', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('transaction_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_detail_id'], ['product_detail.id'], name='fk_offer_product_detail10'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name='fk_deal_transaction1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('fk_deal_transaction1_idx', 'deal', ['transaction_id'], unique=False)
    op.create_table('admin_products',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('brand', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('last_login', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('is_superuser', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=254), nullable=False),
    sa.Column('is_staff', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('date_joined', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('username', 'auth_user', ['username'], unique=True)
    op.create_table('auth_permission',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content_type_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', mysql.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='auth_permission_content_type_id_2f476e4b_fk_django_co'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('auth_permission_content_type_id_codename_01ab375a_uniq', 'auth_permission', ['content_type_id', 'codename'], unique=True)
    op.create_table('posts',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('body', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('slug', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_group',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('name', 'auth_group', ['name'], unique=True)
    op.create_table('ratings',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rateable_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('rateable_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ratings_rateable_type_rateable_id_index', 'ratings', ['rateable_type', 'rateable_id'], unique=False)
    op.create_index('ratings_rateable_type_index', 'ratings', ['rateable_type'], unique=False)
    op.create_index('ratings_rateable_id_index', 'ratings', ['rateable_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('users_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('email_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('type_notification', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['email.id'], name='fk_notification_email1'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='fk_notification_user1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('help_desk',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('deparment_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('users_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('customer_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('subject', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('text', mysql.TEXT(), nullable=False),
    sa.Column('answer', mysql.TEXT(), nullable=True),
    sa.Column('from_email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('from_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='fk_contact_customer1'),
    sa.ForeignKeyConstraint(['deparment_id'], ['deparment.id'], name='contact_category_contact_id_category_contact_id'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='fk_contact_user1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deparment',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('users_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='fk_category_contact_user1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_operation_log',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('method', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=False),
    sa.Column('ip', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('input', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('admin_operation_log_user_id_index', 'admin_operation_log', ['user_id'], unique=False)
    op.create_table('match',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('offer_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ask_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('label', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('tracking_seller', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('tracking_buyer', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('images', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['ask_id'], ['transaction.id'], name='fk_offer_has_offer_offer2'),
    sa.ForeignKeyConstraint(['offer_id'], ['transaction.id'], name='fk_offer_has_offer_offer1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('offer_id', 'match', ['ask_id'], unique=False)
    op.create_index('ask_id', 'match', ['offer_id'], unique=False)
    op.create_table('auth_user_groups',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_user_groups_group_id_97559544_fk_auth_group_id'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_groups_user_id_6a12ed8b_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('auth_user_groups_user_id_group_id_94350c0c_uniq', 'auth_user_groups', ['user_id', 'group_id'], unique=True)
    op.create_table('failed_jobs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('connection', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('queue', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('payload', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('exception', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('failed_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_user_user_permissions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('auth_user_user_permissions_user_id_permission_id_14a6b632_uniq', 'auth_user_user_permissions', ['user_id', 'permission_id'], unique=True)
    op.create_table('category_has_product',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('product_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='category_has_product_category_id_category_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='category_has_product_product_id_product_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('product_id_idx', 'category_has_product', ['product_id'], unique=False)
    op.create_index('category_id_idx', 'category_has_product', ['category_id'], unique=False)
    op.create_table('django_content_type',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('app_label', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('django_content_type_app_label_model_76bd3d3b_uniq', 'django_content_type', ['app_label', 'model'], unique=True)
    op.create_table('role_has_detail',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('role_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('detail_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['detail_id'], ['detail.id'], name='role_has_detail_detail_id_detail_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='role_has_detail_role_id_role_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('role_id_idx', 'role_has_detail', ['role_id'], unique=False)
    op.create_index('detail_id_idx', 'role_has_detail', ['detail_id'], unique=False)
    op.create_table('auth_group_permissions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_group_permissions_group_id_b120cbf9_fk_auth_group_id'),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_group_permissio_permission_id_84c5c92e_fk_auth_perm'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('auth_group_permissions_group_id_permission_id_0cd325b0_uniq', 'auth_group_permissions', ['group_id', 'permission_id'], unique=True)
    op.create_table('admin_roles',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('slug', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('admin_roles_slug_unique', 'admin_roles', ['slug'], unique=True)
    op.create_index('admin_roles_name_unique', 'admin_roles', ['name'], unique=True)
    op.create_table('transaction',
    sa.Column('id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('order_number', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('currency', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('exchange_rate', mysql.FLOAT(precision=18, scale=2), nullable=False),
    sa.Column('conditions', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('box', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('damaged_box', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('expires_at', sa.DATE(), nullable=True),
    sa.Column('amount', mysql.FLOAT(precision=18, scale=2), nullable=True),
    sa.Column('trasaction_fee', mysql.FLOAT(precision=18, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.Column('payment_proc_fee', mysql.FLOAT(precision=18, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.Column('discount', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('ip_address', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('browser', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('device', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('customer_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('product_detail_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('type_transaction', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('transactioncol', mysql.VARCHAR(length=45), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='fk_offer_customer1'),
    sa.ForeignKeyConstraint(['product_detail_id'], ['product_detail.id'], name='fk_offer_product_detail1'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
